sample_sheet: "samplesheet.csv"
reference: "hg38"
ONT: True

#Genome reference
genomes:
  hg38:
    ref: "/mnt/ccrsf-ifx/RefGenomes/hg38_SEQC/hg38.fa"
    gtf: "/mnt/ccrsf-ifx/RefGenomes/hg38/GTF/gencode.v44.annotation.gtf"
    ref_filter: "/mnt/ccrsf-ifx/RefGenomes/hg38_SEQC/hg38.filter.fa"
  mm10:
    ref: "/mnt/ccrsf-ifx/RefGenomes/hg38_SEQC/hg38.fa"
    gtf: "/mnt/ccrsf-ifx/RefGenomes/hg38/GTF/gencode.v44.annotation.gtf"  
  macaca:
    ref: "/mnt/ccrsf-ifx/RefGenomes/MacacaMulatta_RhesusMonkey_v8/fasta/Macaca_mulatta.Mmul_8.0.1.dna.toplevel.fa"  
    gtf: "/mnt/ccrsf-ifx/RefGenomes/MacacaMulatta_RhesusMonkey_v8/Macaca_mulatta.Mmul_8.0.1.95.chr.gtf"

#Cluster assign
large:
  mem: 400000
  time: "96:00:00"
  partition: "norm"
medium:
  mem: 128000
  time: "96:00:00"
  partition: "norm"
small:
  mem: 32000
  time: "96:00:00"
  partition: "norm"
   
