# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.
samples: "config/samples.tsv"
rawpath: "/path/to/rawdata"
analysispath: "/path/to/analysisfolder"
projectname: "John_CS011111_6RNASeq_010124"
conf: "dna_rna"
archive: "path/to/archive"
lib: "T-12U-16B"
primers: "resource/primers.fa"
whitelist: "resource/3M-february-2018-REVERSE-COMPLEMENTED.txt.gz"